// Data shapes mirroring src/lib/*-data.js's { pa, points: [{ t, yRef }] } / { yRef, value } tables.
// Kept as plain value types so the digitized POH data files (Data/PA28*Data.swift, generated by
// scripts/generate-swift-data.mjs) can be simple struct literals.

public struct YRefPoint {
    public let t: Double
    public let yRef: Double
    public init(t: Double, yRef: Double) {
        self.t = t
        self.yRef = yRef
    }
}

public struct PaYRefRow {
    public let pa: Double
    public let points: [YRefPoint]
    public init(pa: Double, points: [YRefPoint]) {
        self.pa = pa
        self.points = points
    }
}

/// Generic (yRef -> value) lookup row — used for dist/time/fuel/tas/rpm tables,
/// which in JS are separate field names (dist, time, fuel, tas, rpm) but share
/// an identical interpolation shape.
public struct YRefValue {
    public let yRef: Double
    public let value: Double
    public init(yRef: Double, value: Double) {
        self.yRef = yRef
        self.value = value
    }
}

public struct IasCasPoint {
    public let ias: Double
    public let cas: Double
    public init(ias: Double, cas: Double) {
        self.ias = ias
        self.cas = cas
    }
}

public struct ClimbData {
    public let yRefLookup: [PaYRefRow]
    public let climbDistLookup: [YRefValue]
    public let timeLookup: [YRefValue]
    public let fuelLookup: [YRefValue]
    public init(yRefLookup: [PaYRefRow], climbDistLookup: [YRefValue], timeLookup: [YRefValue], fuelLookup: [YRefValue]) {
        self.yRefLookup = yRefLookup
        self.climbDistLookup = climbDistLookup
        self.timeLookup = timeLookup
        self.fuelLookup = fuelLookup
    }
}

public struct CruiseData {
    public let cruiseYRefLookup: [PaYRefRow]
    public let cruiseTASLookup: [Int: [YRefValue]]
    public let cruiseMaxTAS: [YRefValue]
    public let cruiseFuelGPH: [Int: Double]
    public let noFairingsTASDeduction: Double
    public init(cruiseYRefLookup: [PaYRefRow], cruiseTASLookup: [Int: [YRefValue]], cruiseMaxTAS: [YRefValue], cruiseFuelGPH: [Int: Double], noFairingsTASDeduction: Double) {
        self.cruiseYRefLookup = cruiseYRefLookup
        self.cruiseTASLookup = cruiseTASLookup
        self.cruiseMaxTAS = cruiseMaxTAS
        self.cruiseFuelGPH = cruiseFuelGPH
        self.noFairingsTASDeduction = noFairingsTASDeduction
    }
}

public struct EngineData {
    public let yRefLookup: [PaYRefRow]
    public let rpmLookup: [Int: [YRefValue]]
    public let engineMaxRPM: [YRefValue]
    public init(yRefLookup: [PaYRefRow], rpmLookup: [Int: [YRefValue]], engineMaxRPM: [YRefValue]) {
        self.yRefLookup = yRefLookup
        self.rpmLookup = rpmLookup
        self.engineMaxRPM = engineMaxRPM
    }
}

public struct AirspeedCalData {
    public let flapsUp: [IasCasPoint]
    public let flaps40: [IasCasPoint]
    public init(flapsUp: [IasCasPoint], flaps40: [IasCasPoint]) {
        self.flapsUp = flapsUp
        self.flaps40 = flaps40
    }
}

public struct AircraftData {
    public let climb: ClimbData
    public let cruise: CruiseData
    public let engine: EngineData
    public let airspeedCal: AirspeedCalData
    public init(climb: ClimbData, cruise: CruiseData, engine: EngineData, airspeedCal: AirspeedCalData) {
        self.climb = climb
        self.cruise = cruise
        self.engine = engine
        self.airspeedCal = airspeedCal
    }
}
